title: NYCU TAKENOKO
description: 國立陽明交通大學 TAKENOKO 日語學習團隊，チームたけのこ。舉辦日文圓桌、日語辯論營、朗讀比賽等活動，在日語學習中培養國際觀。
url: "https://nycutakenoko.github.io"
lang: zh-Hant

# default social-share image; change this one line to swap it site-wide
image: /assets/img/uploads/background-images/1533624717.jpg

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
